/**
 * Generates `.env` — the passcode hash, cookie signing key, and VAPID keypair.
 *
 * Kept out of the server itself deliberately: a default passcode or a derived
 * signing key would quietly defeat the point of having either. Existing values
 * are preserved unless `--force` is passed, so re-running this cannot silently
 * invalidate every phone's session or push subscription.
 *
 *   bun run server/scripts/init-secrets.ts [--passcode 1234] [--force]
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { randomBytes } from "node:crypto";
import webpush from "web-push";
import { Auth } from "../lib/auth";

const ENV_PATH = join(import.meta.dir, "..", "..", ".env");

const args = process.argv.slice(2);
const force = args.includes("--force");
const passcodeArg = args[args.indexOf("--passcode") + 1];
const passcode = args.includes("--passcode") && passcodeArg ? passcodeArg : null;

/** Parses an existing .env into a map, so re-runs are non-destructive. */
function readEnv(path: string): Map<string, string> {
  const values = new Map<string, string>();
  if (!existsSync(path)) return values;
  for (const line of readFileSync(path, "utf8").split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq > 0) values.set(trimmed.slice(0, eq), trimmed.slice(eq + 1));
  }
  return values;
}

const env = readEnv(ENV_PATH);
const kept: string[] = [];
const created: string[] = [];

function ensure(key: string, make: () => string): void {
  if (env.has(key) && !force) {
    kept.push(key);
    return;
  }
  env.set(key, make());
  created.push(key);
}

ensure("SESSION_SECRET", () => randomBytes(32).toString("base64url"));

// Stored base64-encoded: a raw bcrypt hash is full of `$`, and dotenv loaders
// perform shell-style variable expansion on values, which silently corrupts it
// into something that rejects every passcode. See decodePasscodeHash().
if (passcode) {
  const hash = await Auth.hashPasscode(passcode);
  env.set("PASSCODE_HASH_B64", Buffer.from(hash, "utf8").toString("base64"));
  created.push("PASSCODE_HASH_B64");
} else if (!env.has("PASSCODE_HASH_B64")) {
  // An empty value is a working configuration (the gate is simply off), so it
  // must be visibly empty in the file rather than absent and forgotten.
  env.set("PASSCODE_HASH_B64", "");
  created.push("PASSCODE_HASH_B64 (empty — gate disabled)");
} else {
  kept.push("PASSCODE_HASH_B64");
}

if (!env.has("VAPID_PUBLIC_KEY") || !env.has("VAPID_PRIVATE_KEY") || force) {
  const keys = webpush.generateVAPIDKeys();
  env.set("VAPID_PUBLIC_KEY", keys.publicKey);
  env.set("VAPID_PRIVATE_KEY", keys.privateKey);
  created.push("VAPID_PUBLIC_KEY", "VAPID_PRIVATE_KEY");
} else {
  kept.push("VAPID_PUBLIC_KEY", "VAPID_PRIVATE_KEY");
}

ensure("VAPID_SUBJECT", () => "mailto:shahi@localhost");

const body = [
  "# Shahi secrets. Generated by server/scripts/init-secrets.ts — do not commit.",
  "#",
  "# PASSCODE_HASH_B64  base64 of the bcrypt hash of the app passcode; empty",
  "#                    disables the gate. Base64 because dotenv loaders expand",
  "#                    `$` in values and would corrupt a raw bcrypt hash.",
  "#                    Set with: bun run server/scripts/init-secrets.ts --passcode 1234",
  "# SESSION_SECRET HMAC key for session cookies. Rotating it signs every device out.",
  "# VAPID_*        Web Push keypair. Rotating it invalidates every push subscription.",
  "",
  ...[...env].map(([k, v]) => `${k}=${v}`),
  "",
].join("\n");

writeFileSync(ENV_PATH, body, { mode: 0o600 });

console.log(`wrote ${ENV_PATH} (mode 0600)`);
if (created.length) console.log(`  created: ${created.join(", ")}`);
if (kept.length) console.log(`  kept:    ${kept.join(", ")}`);

if (!env.get("PASSCODE_HASH_B64")) {
  console.log(
    "\n  No passcode set. Anyone who can reach the port has full control of every\n" +
      "  agent on this machine. Set one before publishing over Tailscale:\n" +
      "    bun run server/scripts/init-secrets.ts --passcode <digits>",
  );
}
