/**
 * Runtime configuration, read from the environment.
 *
 * Secrets live in `.env` (git-ignored) and are generated by
 * `bun run server/scripts/init-secrets.ts` rather than being invented here — a
 * default passcode or a hardcoded signing key would defeat the point of having
 * either.
 */
import { homedir } from "node:os";
import { join } from "node:path";

export interface Config {
  /**
   * Interface to bind. Defaults to loopback.
   *
   * Widen this deliberately, not casually: herdr's own socket has no
   * authentication and this process proxies every one of its methods, so the
   * bind address plus the passcode are the entire security boundary.
   *
   * Prefer a specific Tailscale address (`100.x.y.z`) over `0.0.0.0`. Binding
   * all interfaces also publishes on the LAN, which is a much larger audience
   * than the tailnet and almost never what is intended.
   *
   * Note that anything other than loopback means the browser no longer treats
   * the page as a secure context, so service workers will not register and Web
   * Push stops working. `tailscale serve` avoids that by terminating real TLS
   * in front of a loopback bind.
   */
  host: string;
  port: number;
  socketPath: string;
  /** SQLite file for transcripts and push subscriptions. */
  dataPath: string;
  /** Decoded bcrypt hash of the passcode. Empty disables the gate entirely. */
  passcodeHash: string;
  /** HMAC key for session cookies. */
  sessionSecret: string;
  /** How long a phone stays signed in. */
  sessionTtlMs: number;
  vapid: { publicKey: string; privateKey: string; subject: string } | null;
  /** Directory of built frontend assets, when serving them from this process. */
  webRoot: string | null;
}

const DEFAULT_PORT = 7171;

function required(name: string, value: string | undefined, hint: string): string {
  if (!value) {
    throw new Error(`${name} is not set. ${hint}`);
  }
  return value;
}

const BCRYPT_RE = /^\$2[aby]\$\d{2}\$[./A-Za-z0-9]{53}$/;

/**
 * Decodes the base64-wrapped bcrypt hash.
 *
 * The wrapping is not decoration. A bcrypt hash is full of `$`, and Bun's dotenv
 * loader performs shell-style variable expansion on values — including inside
 * single *and* double quotes — so `$2b$12$...` silently loads as a mangled
 * fragment with `$2b` and `$12` expanded away to nothing. The result still
 * verifies cleanly against every passcode as *false*, so the failure looks
 * exactly like a wrong passcode and nothing in the logs says otherwise.
 *
 * Base64 has no `$` and survives every env loader unchanged; escaping with `\$`
 * also works in Bun but is interpreted differently by systemd EnvironmentFile
 * and by docker, so it is not portable.
 */
function decodePasscodeHash(encoded: string | undefined): string {
  if (!encoded) return "";

  const hash = Buffer.from(encoded, "base64").toString("utf8");
  if (!BCRYPT_RE.test(hash)) {
    throw new Error(
      "PASSCODE_HASH_B64 did not decode to a bcrypt hash. Regenerate it with " +
        "`bun run server/scripts/init-secrets.ts --passcode <digits>`, and note " +
        "that the value must be base64 — a raw bcrypt hash is corrupted by " +
        "dotenv variable expansion.",
    );
  }
  return hash;
}

export function loadConfig(env: NodeJS.ProcessEnv = process.env): Config {
  const vapidPublic = env.VAPID_PUBLIC_KEY;
  const vapidPrivate = env.VAPID_PRIVATE_KEY;

  return {
    host: env.HOST ?? "127.0.0.1",
    port: Number(env.PORT ?? DEFAULT_PORT),
    socketPath: env.HERDR_SOCKET_PATH ?? join(homedir(), ".config", "herdr", "herdr.sock"),
    dataPath: env.HERDRUI_DATA ?? join(homedir(), ".local", "share", "herdrui", "herdrui.sqlite"),
    passcodeHash: decodePasscodeHash(env.PASSCODE_HASH_B64),
    sessionSecret: required(
      "SESSION_SECRET",
      env.SESSION_SECRET,
      "Run `bun run server/scripts/init-secrets.ts` to generate one.",
    ),
    sessionTtlMs: Number(env.SESSION_TTL_MS ?? 30 * 24 * 60 * 60 * 1000),
    vapid:
      vapidPublic && vapidPrivate
        ? {
            publicKey: vapidPublic,
            privateKey: vapidPrivate,
            subject: env.VAPID_SUBJECT ?? "mailto:herdrui@localhost",
          }
        : null,
    webRoot: env.WEB_ROOT ?? null,
  };
}
