/**
 * The `.env` file: where it is, how it is read, and how its secrets are made.
 *
 * Two things generate secrets — `scripts/init-secrets.ts` for a checkout and
 * the herdr plugin's startup hook for a managed install — and they must agree
 * on every detail (the base64 wrapping of the passcode hash, what "already
 * set" means, the file's mode), so the generation lives here and both call it.
 *
 * Where the file lives is decided by `SHAHI_ENV_FILE`. Without it, the file is
 * `.env` at the repo root, which is what a checkout expects. The plugin sets it
 * to a path under herdr's per-plugin config directory, because a plugin root
 * is a managed checkout that a reinstall replaces — secrets kept there would
 * be lost on the first update.
 */
import { chmodSync, existsSync, readFileSync, writeFileSync, renameSync } from "node:fs";
import { join } from "node:path";
import { randomBytes } from "node:crypto";
import webpush from "web-push";
import { Auth } from "./auth";

export function envFilePath(env: NodeJS.ProcessEnv = process.env): string {
  return env.SHAHI_ENV_FILE ?? join(import.meta.dir, "..", "..", ".env");
}

/**
 * Parses a `.env` into a map. No variable expansion, on purpose: Bun's own
 * loader expands `$` inside values, which is why the passcode hash is stored
 * base64-wrapped in the first place (see config.ts).
 */
export function readEnvFile(path: string): Map<string, string> {
  const values = new Map<string, string>();
  if (!existsSync(path)) return values;
  for (const line of readFileSync(path, "utf8").split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq > 0) values.set(trimmed.slice(0, eq), trimmed.slice(eq + 1));
  }
  return values;
}

export interface SecretsReport {
  env: Map<string, string>;
  created: string[];
  kept: string[];
}

/**
 * Fills in whatever secrets `env` lacks, and reports which is which. Existing
 * values are kept unless `force` — regenerating SESSION_SECRET signs every
 * phone out and regenerating the VAPID pair drops every push subscription, so
 * neither may happen by accident.
 *
 * `passcode` sets the passcode; `null` leaves an existing hash alone, and if
 * there is none, records the gate as visibly off rather than absent and
 * forgotten.
 */
export async function ensureSecrets(
  env: Map<string, string>,
  opts: { passcode?: string | null; force?: boolean } = {},
): Promise<SecretsReport> {
  const force = opts.force ?? false;
  const created: string[] = [];
  const kept: string[] = [];

  const ensure = (key: string, make: () => string) => {
    if (env.has(key) && !force) {
      kept.push(key);
      return;
    }
    env.set(key, make());
    created.push(key);
  };

  ensure("SESSION_SECRET", () => randomBytes(32).toString("base64url"));

  // Stored base64-encoded: a raw bcrypt hash is full of `$`, and dotenv loaders
  // perform shell-style variable expansion on values, which silently corrupts it
  // into something that rejects every passcode. See decodePasscodeHash().
  if (opts.passcode) {
    const hash = await Auth.hashPasscode(opts.passcode);
    env.set("PASSCODE_HASH_B64", Buffer.from(hash, "utf8").toString("base64"));
    created.push("PASSCODE_HASH_B64");
  } else if (!env.has("PASSCODE_HASH_B64")) {
    env.set("PASSCODE_HASH_B64", "");
    created.push("PASSCODE_HASH_B64 (empty — gate disabled)");
  } else {
    kept.push("PASSCODE_HASH_B64");
  }

  if (!env.has("VAPID_PUBLIC_KEY") || !env.has("VAPID_PRIVATE_KEY") || force) {
    const keys = webpush.generateVAPIDKeys();
    env.set("VAPID_PUBLIC_KEY", keys.publicKey);
    env.set("VAPID_PRIVATE_KEY", keys.privateKey);
    created.push("VAPID_PUBLIC_KEY", "VAPID_PRIVATE_KEY");
  } else {
    kept.push("VAPID_PUBLIC_KEY", "VAPID_PRIVATE_KEY");
  }

  ensure("VAPID_SUBJECT", () => "mailto:shahi@localhost");

  return { env, created, kept };
}

/**
 * A passcode of the kind install.sh hands out: four digits, because it is
 * typed on a phone behind a tailnet, and the boundary that matters is the
 * network rather than the length of this.
 */
export function randomPasscode(): string {
  return String(1000 + (randomBytes(2).readUInt16BE(0) % 9000));
}

export function renderEnvFile(env: Map<string, string>): string {
  return [
    "# Shahi secrets. Generated by server/lib/secrets.ts — do not commit.",
    "#",
    "# PASSCODE_HASH_B64  base64 of the bcrypt hash of the app passcode; empty",
    "#                    disables the gate. Base64 because dotenv loaders expand",
    "#                    `$` in values and would corrupt a raw bcrypt hash.",
    "#                    Set with: bun run server/scripts/init-secrets.ts --passcode 1234",
    "# SESSION_SECRET HMAC key for session cookies. Rotating it signs every device out.",
    "# VAPID_*        Web Push keypair. Rotating it invalidates every push subscription.",
    "# RELAY_URL      The blind relay this box dials so a phone reaches it from anywhere",
    "#                (docs/relay.md). Under the herdr plugin, no line means Shahi's",
    "#                relay; RELAY_URL= (empty) means direct only; a URL means yours.",
    "# PORT, HOST     Where the sidecar listens; 7171 on loopback unless set.",
    "",
    ...[...env].map(([k, v]) => `${k}=${v}`),
    "",
  ].join("\n");
}

/**
 * Writes the `.env` atomically: a fresh 0600 temp file, then a rename over the
 * path. Rewriting in place kept the same inode, so a co-user who had opened a
 * hand-made 0644 file read-only (the docs' `echo RELAY_URL= >> .env` pre-seed
 * step) kept reading the session key and VAPID secret written into it after the
 * chmod (pentest L8). A rename gives that descriptor the old, empty inode and
 * the secrets land on a new one that was never anything but 0600.
 */
export function writeEnvFile(path: string, env: Map<string, string>): void {
  const tmp = `${path}.${randomBytes(6).toString("hex")}.tmp`;
  writeFileSync(tmp, renderEnvFile(env), { mode: 0o600 });
  chmodSync(tmp, 0o600); // umask can clear bits at create time; pin them before the rename
  renameSync(tmp, path);
}
