/** Canonical Shahi palette shared by native UI and generated web/assets. */
export const brandColors = {
  void: "#0E0D0B",
  surface: "#14120F",
  raised: "#1C1915",
  line: "#2A2620",
  lineBright: "#3A352C",
  text: "#F0EFEA",
  muted: "#A6A099",
  accent: "#E8A33D",
  working: "#8BB8E8",
  success: "#5FB88A",
  danger: "#D96A4A",
} as const;

/** Shahi identity geometry. Asset exports are generated by scripts/brand-assets.ts. */
export const brandMark = {
  cursor: { x: 44, y: 10, width: 12, height: 12, rx: 2 },
  glass: "M22 34H78L71 72Q70 80 62 80H38Q30 80 29 72Z",
} as const;

/** Outlined lettering shared by native lockups and generated assets. */
export const brandWordmark = {
  width: 180,
  height: 76,
  viewBox: "0 0 180 76",
  translateX: 4,
  strokeWidth: 5.5,
  path: "M29 33C24 28 8 29 8 38C8 48 30 41 30 52C30 62 13 64 7 57M44 13V60M44 41C44 27 68 26 68 42V60M106 33V60M106 43C106 26 82 26 82 45C82 65 106 65 106 48M122 13V60M122 41C122 27 146 26 146 42V60M163 32V60",
  dot: { x: 160, y: 14, width: 6, height: 6, rx: 1.5 },
} as const;

/** Existing native agent artwork; keep provider identity consistent across clients. */
export const agentMarks = {"claudecode": "M21 10.5h3v3h-3v3h-1.5v3H18v-3h-1.5v3H15v-3H9v3H7.5v-3H6v3H4.5v-3H3v-3H0v-3h3v-6h18Zm-15 0h1.5v-3H6Zm10.5 0H18v-3h-1.5z", "openai": "M22.282 9.821a6 6 0 0 0-.516-4.91a6.05 6.05 0 0 0-6.51-2.9A6.065 6.065 0 0 0 4.981 4.18a6 6 0 0 0-3.998 2.9a6.05 6.05 0 0 0 .743 7.097a5.98 5.98 0 0 0 .51 4.911a6.05 6.05 0 0 0 6.515 2.9A6 6 0 0 0 13.26 24a6.06 6.06 0 0 0 5.772-4.206a6 6 0 0 0 3.997-2.9a6.06 6.06 0 0 0-.747-7.073M13.26 22.43a4.48 4.48 0 0 1-2.876-1.04l.141-.081l4.779-2.758a.8.8 0 0 0 .392-.681v-6.737l2.02 1.168a.07.07 0 0 1 .038.052v5.583a4.504 4.504 0 0 1-4.494 4.494M3.6 18.304a4.47 4.47 0 0 1-.535-3.014l.142.085l4.783 2.759a.77.77 0 0 0 .78 0l5.843-3.369v2.332a.08.08 0 0 1-.033.062L9.74 19.95a4.5 4.5 0 0 1-6.14-1.646M2.34 7.896a4.5 4.5 0 0 1 2.366-1.973V11.6a.77.77 0 0 0 .388.677l5.815 3.354l-2.02 1.168a.08.08 0 0 1-.071 0l-4.83-2.786A4.504 4.504 0 0 1 2.34 7.872zm16.597 3.855l-5.833-3.387L15.119 7.2a.08.08 0 0 1 .071 0l4.83 2.791a4.494 4.494 0 0 1-.676 8.105v-5.678a.79.79 0 0 0-.407-.667m2.01-3.023l-.141-.085l-4.774-2.782a.78.78 0 0 0-.785 0L9.409 9.23V6.897a.07.07 0 0 1 .028-.061l4.83-2.787a4.5 4.5 0 0 1 6.68 4.66zm-12.64 4.135l-2.02-1.164a.08.08 0 0 1-.038-.057V6.075a4.5 4.5 0 0 1 7.375-3.453l-.142.08L8.704 5.46a.8.8 0 0 0-.393.681zm1.097-2.365l2.602-1.5l2.607 1.5v2.999l-2.597 1.5l-2.607-1.5Z"} as const;
